name: python-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt ( pip install -r requirements.txt ) else ( echo "no requirements.txt" )
          pip install pytest

      - name: Lint (flake8 si dispo)
        run: |
          pip install flake8 || exit 0
          flake8 . || echo "flake8 warnings only"

      - name: Run tests (si présents)
        run: |
          if exist tests ( pytest -q ) else ( echo "no tests/" )
